#!/usr/bin/env bash
#Displaying username, user id, and home directory from /etc/passwd

while IFS=: read -r username _ userid _ _ _ homedir _; do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $homedir"
    echo "----------------------"
done < /etc/passwd
