#!/usr/bin/env bash
# this script manages manage_my script

PIDFILE="/var/run/my_process.pid"
PROCESS="./manage_my_process"

case "$1" in
    start)
        $PROCESS &
        echo $! > "$PIDFILE"
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f "$PIDFILE" ]; then
            kill "$(cat $PIDFILE)" 2>/dev/null
            rm -f "$PIDFILE"
            echo "manage_my_process stopped"
        else
            echo "No PID file found, process may not be running"
        fi
        ;;
    restart)
        if [ -f "$PIDFILE" ]; then
            kill "$(cat $PIDFILE)" 2>/dev/null
            rm -f "$PIDFILE"
        fi
        $PROCESS &
        echo $! > "$PIDFILE"
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac

